services:
  postgres:
    image: postgres:16-alpine
    container_name: shopping_db
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: py_arch_lab
      POSTGRES_PASSWORD: py_arch_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U py_arch_lab"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: